workflows:
  android-workflow:
    name: Ambition Bac Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Activer Swift Package Manager
        script: flutter config --enable-swift-package-manager
      - name: Flutter Clean and Fetch
        script: |
          flutter pub cache clean --force
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-workflow:
    name: Ambition Bac iOS Build
    max_build_duration: 90
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ambition.ambitionbac
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
